apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: ehabshaaban/producer:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: openaq-api-key
              key: api-key
