apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ehabshaaban/consumer:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: openaq-api-key
              key: api-key
